import type { Maquina } from "./types";
import { conf, est, pend, na } from "./types";

/**
 * Plataformas de tijera.
 *
 * Todas las cifras salen de las fichas técnicas en PDF que JOFEMESA sirve
 * desde su propio servidor (`/public/fichas/`), transcritas a mano desde
 * `data/raw/fichas/`. Lo que la ficha no dice va como `pend()`, nunca
 * aproximado.
 *
 * Dos avisos sobre el origen de los ficheros:
 *
 * 1. `genie-gs-3394rt.pdf` y `haulotte-2030-3246es.pdf` son, por su
 *    contenido, fichas de JLG Industries (llevan su copyright y sus
 *    designaciones: 3394RT/4394RT y la serie ES). El nombre del fichero no
 *    coincide con el fabricante real, así que aquí se respeta lo que dice el
 *    documento: `fabricante: "JLG"`. Conviene confirmarlo con el cliente.
 * 2. Una misma ficha cubre varios modelos. Eso es correcto: el PDF que se
 *    descarga es el mismo para toda la familia.
 */

/** Las ocho delegaciones. Cualquier tijera se pide desde todas. */
const TODAS = [
  "madrid",
  "asturias",
  "valencia",
  "castellon",
  "malaga",
  "sevilla",
  "valladolid",
  "alicante",
] as const;

/** Ficheros reales de /public/fichas con su tamaño en bytes. */
const FICHA = {
  gs1932: { src: "/fichas/genie-gs-1932.pdf", bytes: 2472274 },
  gs2632: { src: "/fichas/genie-gs-2632.pdf", bytes: 2335830 },
  gs3268rt: { src: "/fichas/genie-gs-2668-3268rt.pdf", bytes: 762848 },
  gs3390rt: { src: "/fichas/genie-gs-3390-4390-5390rt.pdf", bytes: 871888 },
  gs3394rt: { src: "/fichas/jlg-3394-4394rt.pdf", bytes: 479876 },
  gs4047: { src: "/fichas/genie-gs-4047.pdf", bytes: 3969968 },
  jlgEs: { src: "/fichas/jlg-serie-es.pdf", bytes: 54543 },
  compact: { src: "/fichas/haulotte-compact-8-10.pdf", bytes: 1262235 },
  hsx: { src: "/fichas/haulotte-h-sx.pdf", bytes: 873869 },
} as const;

/** Specs del registro que no tienen sentido en una tijera. */
const NO_APLICA_EN_TIJERA = {
  alcanceHorizontal: na<number>(),
  alturaElevacion: na<number>(),
  rotacionTorreta: na<number>(),
  potencia: na<number>(),
  profundidadExcavacion: na<number>(),
} as const;

export const MAQUINAS_TIJERAS: Maquina[] = [
  /* ==========================================================
     Genie — tijeras eléctricas de interior (ficha GS-1530/1532/1930/1932)
     ========================================================== */
  {
    id: "genie-gs1530",
    slug: "genie-gs-1530",
    modelo: "GS-1530",
    marca: "Genie",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 10,
    facetas: {
      energia: "electrico",
      entornos: ["interior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(6.4, "ficha-pdf"),
      alturaPlataforma: conf(4.4, "ficha-pdf"),
      capacidadCarga: conf(272, "ficha-pdf"),
      personas: est(
        2,
        "ficha-pdf",
        "La ficha da 2/– (interior/exterior): dos operarios en interior y ningún uso homologado en exterior.",
      ),
      anchoTransporte: conf(760, "ficha-pdf"),
      longitudTransporte: conf(1830, "ficha-pdf"),
      alturaTransporte: est(1730,
        "ficha-pdf",
        "1,73 m con las barandillas abatidas; 2,03 m con las barandillas montadas.",
      ),
      extensionPlataforma: conf(0.91, "ficha-pdf"),
      radioGiroInterior: conf(0, "ficha-pdf"),
      pendienteSuperable: conf(30, "ficha-pdf"),
      peso: conf(1233, "ficha-pdf"),
      velocidadTraslacion: est(
        4,
        "ficha-pdf",
        "4,0 km/h replegada; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf("Eléctrico 24 V CC (4 baterías de 6 V y 225 Ah)", "ficha-pdf"),
    },
    descripcionCorta:
      "Tijera eléctrica de 6,40 m de altura de trabajo y 0,76 m de ancho, solo para interior.",
    aplicaciones: [
      "Mantenimiento de luminarias y falsos techos",
      "Instalaciones en locales comerciales",
      "Trabajos en pasillos y zonas estrechas",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs1932,
    trabajos: ["altura"],
    notaAsesor:
      "Si tienes que cruzar una puerta estándar con la máquina, esta es la que entra.",
  },
  {
    id: "genie-gs1532",
    slug: "genie-gs-1532",
    modelo: "GS-1532",
    marca: "Genie",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 20,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(6.4, "ficha-pdf"),
      alturaPlataforma: conf(4.4, "ficha-pdf"),
      capacidadCarga: conf(272, "ficha-pdf"),
      personas: est(
        1,
        "ficha-pdf",
        "La ficha da 2/1 (interior/exterior): dos operarios en interior, uno en exterior.",
      ),
      anchoTransporte: conf(813, "ficha-pdf"),
      longitudTransporte: conf(1830, "ficha-pdf"),
      alturaTransporte: est(1730,
        "ficha-pdf",
        "1,73 m con las barandillas abatidas; 2,03 m con las barandillas montadas.",
      ),
      extensionPlataforma: conf(0.91, "ficha-pdf"),
      radioGiroInterior: conf(0, "ficha-pdf"),
      pendienteSuperable: conf(30, "ficha-pdf"),
      peso: conf(1269, "ficha-pdf"),
      velocidadTraslacion: est(
        4,
        "ficha-pdf",
        "4,0 km/h replegada; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf("Eléctrico 24 V CC (4 baterías de 6 V y 225 Ah)", "ficha-pdf"),
    },
    descripcionCorta:
      "La misma tijera de 6,40 m que la GS-1530, pero homologada también para exterior.",
    aplicaciones: [
      "Mantenimiento en nave con salidas al patio",
      "Montaje de rótulos a baja altura",
      "Trabajos de electricidad y climatización",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs1932,
    trabajos: ["altura"],
    notaAsesor:
      "Cuesta lo mismo que la 1530 y sí puede salir fuera: si hay dudas, coge esta.",
  },
  {
    id: "genie-gs1930",
    slug: "genie-gs-1930",
    modelo: "GS-1930",
    marca: "Genie",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 30,
    facetas: {
      energia: "electrico",
      entornos: ["interior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(7.6, "ficha-pdf"),
      alturaPlataforma: conf(5.6, "ficha-pdf"),
      capacidadCarga: conf(227, "ficha-pdf"),
      personas: est(
        2,
        "ficha-pdf",
        "La ficha da 2/– (interior/exterior): dos operarios en interior y ningún uso homologado en exterior.",
      ),
      anchoTransporte: conf(760, "ficha-pdf"),
      longitudTransporte: conf(1830, "ficha-pdf"),
      alturaTransporte: est(1750,
        "ficha-pdf",
        "1,75 m con las barandillas abatidas; 2,11 m con las barandillas montadas.",
      ),
      extensionPlataforma: conf(0.91, "ficha-pdf"),
      radioGiroInterior: conf(0, "ficha-pdf"),
      pendienteSuperable: conf(25, "ficha-pdf"),
      peso: conf(1498, "ficha-pdf"),
      velocidadTraslacion: est(
        4,
        "ficha-pdf",
        "4,0 km/h replegada; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf("Eléctrico 24 V CC (4 baterías de 6 V y 225 Ah)", "ficha-pdf"),
    },
    descripcionCorta:
      "Tijera eléctrica estrecha de 7,60 m de altura de trabajo, de uso exclusivo en interior.",
    aplicaciones: [
      "Mantenimiento de instalaciones en nave",
      "Montaje de conductos y bandejas",
      "Reposición en almacén de estanterías altas",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs1932,
    trabajos: ["altura"],
    notaAsesor:
      "Es la talla de nave por defecto; comprueba antes que el suelo esté liso y sin desniveles.",
  },
  {
    id: "genie-gs1932",
    slug: "genie-gs-1932",
    modelo: "GS-1932",
    marca: "Genie",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: true,
    orden: 40,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(7.6, "ficha-pdf"),
      alturaPlataforma: conf(5.6, "ficha-pdf"),
      capacidadCarga: conf(227, "ficha-pdf"),
      personas: est(
        1,
        "ficha-pdf",
        "La ficha da 2/1 (interior/exterior): dos operarios en interior, uno en exterior.",
      ),
      anchoTransporte: conf(813, "ficha-pdf"),
      longitudTransporte: conf(1830, "ficha-pdf"),
      alturaTransporte: est(1750,
        "ficha-pdf",
        "1,75 m con las barandillas abatidas; 2,11 m con las barandillas montadas.",
      ),
      extensionPlataforma: conf(0.91, "ficha-pdf"),
      radioGiroInterior: conf(0, "ficha-pdf"),
      pendienteSuperable: conf(25, "ficha-pdf"),
      peso: conf(1503, "ficha-pdf"),
      velocidadTraslacion: est(
        4,
        "ficha-pdf",
        "4,0 km/h replegada; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf("Eléctrico 24 V CC (4 baterías de 6 V y 225 Ah)", "ficha-pdf"),
    },
    descripcionCorta:
      "Tijera eléctrica de 7,60 m, estrecha y homologada para interior y exterior.",
    aplicaciones: [
      "Mantenimiento eléctrico y de climatización",
      "Montaje de instalaciones en nave",
      "Trabajos de pintura y señalización a media altura",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs1932,
    trabajos: ["altura"],
    notaAsesor:
      "Si el suelo es liso y hay corriente para cargar, una eléctrica como esta sale más barata que cualquier diésel.",
  },

  /* ==========================================================
     Genie — tijeras eléctricas de cesta ancha (ficha GS-2032/2632/3232)
     ========================================================== */
  {
    id: "genie-gs2032",
    slug: "genie-gs-2032",
    modelo: "GS-2032",
    marca: "Genie",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 60,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(7.9, "ficha-pdf"),
      alturaPlataforma: conf(5.9, "ficha-pdf"),
      capacidadCarga: conf(363, "ficha-pdf"),
      personas: est(
        1,
        "ficha-pdf",
        "La ficha da 2/1 (interior/exterior): dos operarios en interior, uno en exterior.",
      ),
      anchoTransporte: conf(810, "ficha-pdf"),
      longitudTransporte: conf(2440, "ficha-pdf"),
      alturaTransporte: est(1780,
        "ficha-pdf",
        "1,78 m con las barandillas abatidas; 2,13 m con las barandillas montadas.",
      ),
      extensionPlataforma: conf(0.91, "ficha-pdf"),
      radioGiroInterior: conf(0, "ficha-pdf"),
      pendienteSuperable: conf(30, "ficha-pdf"),
      peso: conf(1825, "ficha-pdf"),
      velocidadTraslacion: est(
        3.5,
        "ficha-pdf",
        "3,5 km/h replegada; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf("Eléctrico 24 V CC (4 baterías de 6 V y 225 Ah)", "ficha-pdf"),
    },
    descripcionCorta:
      "Tijera eléctrica de 7,90 m con 363 kg de carga y cesta de 2,26 m, para interior y exterior.",
    aplicaciones: [
      "Montaje de instalaciones con material voluminoso",
      "Mantenimiento industrial en nave",
      "Trabajos con dos operarios y herramienta",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs2632,
    trabajos: ["altura"],
    notaAsesor:
      "Cuando la queja es «no me cabe el material en la cesta», sube de la 1932 a esta.",
  },
  {
    id: "genie-gs2632",
    slug: "genie-gs-2632",
    modelo: "GS-2632",
    marca: "Genie",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 110,
    facetas: {
      energia: "electrico",
      entornos: ["interior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(9.8, "ficha-pdf"),
      alturaPlataforma: conf(7.8, "ficha-pdf"),
      capacidadCarga: conf(227, "ficha-pdf"),
      personas: est(
        2,
        "ficha-pdf",
        "La ficha da 2/– (interior/exterior) y marca el modelo como de uso exclusivo en interior.",
      ),
      anchoTransporte: conf(810, "ficha-pdf"),
      longitudTransporte: conf(2440, "ficha-pdf"),
      alturaTransporte: est(1910,
        "ficha-pdf",
        "1,91 m con las barandillas abatidas; 2,26 m con las barandillas montadas.",
      ),
      extensionPlataforma: conf(0.91, "ficha-pdf"),
      radioGiroInterior: conf(0, "ficha-pdf"),
      pendienteSuperable: conf(25, "ficha-pdf"),
      peso: conf(1956, "ficha-pdf"),
      velocidadTraslacion: est(
        3.5,
        "ficha-pdf",
        "3,5 km/h replegada; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf("Eléctrico 24 V CC (4 baterías de 6 V y 225 Ah)", "ficha-pdf"),
    },
    descripcionCorta:
      "Tijera eléctrica de 9,80 m con cesta larga, de uso exclusivo en interior.",
    aplicaciones: [
      "Mantenimiento de cubiertas y luminarias en nave alta",
      "Montaje de instalaciones bajo cubierta",
      "Montaje de escenografía y estructuras de evento en interior",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs2632,
    trabajos: ["altura"],
    notaAsesor:
      "Solo interior: si el trabajo tiene un tramo en el patio, no es esta máquina.",
  },
  {
    id: "genie-gs3232",
    slug: "genie-gs-3232",
    modelo: "GS-3232",
    marca: "Genie",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: true,
    orden: 160,
    facetas: {
      energia: "electrico",
      entornos: ["interior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(11.5, "ficha-pdf"),
      alturaPlataforma: conf(9.5, "ficha-pdf"),
      capacidadCarga: conf(227, "ficha-pdf"),
      personas: est(
        2,
        "ficha-pdf",
        "La ficha da 2/– (interior/exterior) y marca el modelo como de uso exclusivo en interior.",
      ),
      anchoTransporte: conf(810, "ficha-pdf"),
      longitudTransporte: conf(2440, "ficha-pdf"),
      alturaTransporte: est(2030,
        "ficha-pdf",
        "2,03 m con las barandillas abatidas; 2,39 m con las barandillas montadas.",
      ),
      extensionPlataforma: conf(0.91, "ficha-pdf"),
      radioGiroInterior: conf(0, "ficha-pdf"),
      pendienteSuperable: conf(25, "ficha-pdf"),
      peso: conf(2352, "ficha-pdf"),
      velocidadTraslacion: est(
        3.5,
        "ficha-pdf",
        "3,5 km/h replegada; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf("Eléctrico 24 V CC (4 baterías de 6 V y 225 Ah)", "ficha-pdf"),
    },
    descripcionCorta:
      "Tijera eléctrica de 11,50 m y 0,81 m de ancho, con estabilizadores de nivelación automática.",
    aplicaciones: [
      "Mantenimiento bajo cubierta en naves altas",
      "Instalación de iluminación y detección de incendios",
      "Montajes en pabellones y recintos feriales",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs2632,
    trabajos: ["altura"],
    notaAsesor:
      "Once metros y medio pasando por pasillos de menos de un metro: no hay muchas máquinas que hagan eso.",
  },

  /* ==========================================================
     Genie GS-4047 — eléctrica de gran altura
     ========================================================== */
  {
    id: "genie-gs4047",
    slug: "genie-gs-4047",
    modelo: "GS-4047",
    marca: "Genie",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 230,
    facetas: {
      energia: "electrico",
      entornos: ["interior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(13.7, "ficha-pdf"),
      alturaPlataforma: conf(11.7, "ficha-pdf"),
      capacidadCarga: conf(350, "ficha-pdf"),
      personas: est(
        3,
        "ficha-pdf",
        "La ficha da 3/– (interior/exterior) y marca el modelo como de uso exclusivo en interior.",
      ),
      anchoTransporte: conf(1190, "ficha-pdf"),
      longitudTransporte: conf(2440, "ficha-pdf"),
      alturaTransporte: est(1880,
        "ficha-pdf",
        "1,88 m con las barandillas abatidas; 2,54 m con las barandillas montadas.",
      ),
      extensionPlataforma: conf(0.91, "ficha-pdf"),
      radioGiroInterior: conf(0, "ficha-pdf"),
      pendienteSuperable: conf(25, "ficha-pdf"),
      peso: conf(3221, "ficha-pdf"),
      velocidadTraslacion: est(
        3.1,
        "ficha-pdf",
        "3,1 km/h replegada; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf(
        "Eléctrico 48 V CC, 300 Ah (4 baterías de 12 V y 150 Ah en serie-paralelo)",
        "ficha-pdf",
      ),
    },
    descripcionCorta:
      "Tijera eléctrica de 13,70 m y tres operarios en plataforma, para interior.",
    aplicaciones: [
      "Mantenimiento de estructuras y cubiertas en naves altas",
      "Montajes industriales con equipo de tres operarios",
      "Instalaciones en pabellones y centros logísticos",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs4047,
    trabajos: ["altura"],
    notaAsesor:
      "Antes de mandarla, confirma que el suelo aguanta tres toneladas y que el acceso tiene 1,20 m libres.",
  },

  /* ==========================================================
     Genie RT — tijeras diésel todoterreno (ficha GS-2668RT/3268RT)
     ========================================================== */
  {
    id: "genie-gs2668rt",
    slug: "genie-gs-2668rt",
    modelo: "GS-2668RT",
    marca: "Genie",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-diesel",
    lineas: ["alquiler"],
    destacada: false,
    orden: 130,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(9.92, "ficha-pdf"),
      alturaPlataforma: conf(7.92, "ficha-pdf"),
      capacidadCarga: conf(567, "ficha-pdf"),
      personas: conf(4, "ficha-pdf"),
      anchoTransporte: conf(1730, "ficha-pdf"),
      longitudTransporte: conf(2670, "ficha-pdf"),
      alturaTransporte: est(1700,
        "ficha-pdf",
        "1,70 m con las barandillas replegadas; 2,32 m con las barandillas montadas.",
      ),
      extensionPlataforma: conf(1.1, "ficha-pdf"),
      radioGiroInterior: conf(1.52, "ficha-pdf"),
      pendienteSuperable: conf(35, "ficha-pdf"),
      peso: est(
        3263,
        "ficha-pdf",
        "Configuración CE diésel 4x4 con neumáticos rellenos de espuma; los estabilizadores suman 483 kg.",
      ),
      velocidadTraslacion: est(
        6.1,
        "ficha-pdf",
        "6,1 km/h replegada; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf(
        "Kubota D-1105 diésel 24,9 CV; opciones Kubota gasolina/GLP 23 CV y Perkins 403D-11 diésel 26 CV",
        "ficha-pdf",
      ),
    },
    descripcionCorta:
      "Tijera diésel 4x4 de 9,92 m con 567 kg de carga y cuatro operarios en plataforma.",
    aplicaciones: [
      "Trabajos de fachada y cerramientos",
      "Obra civil y urbanización",
      "Mantenimiento de instalaciones exteriores",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs3268rt,
    trabajos: ["altura"],
    notaAsesor:
      "Si el terreno no está compactado o hay barro, olvídate de la eléctrica y vete directo a una RT como esta.",
  },
  {
    id: "genie-gs3268rt",
    slug: "genie-gs-3268rt",
    modelo: "GS-3268RT",
    marca: "Genie",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-diesel",
    lineas: ["alquiler"],
    destacada: true,
    orden: 180,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(11.75, "ficha-pdf"),
      alturaPlataforma: conf(9.75, "ficha-pdf"),
      capacidadCarga: conf(454, "ficha-pdf"),
      personas: est(
        2,
        "ficha-pdf",
        "La ficha da 4/2 (interior/exterior): cuatro operarios en interior, dos en exterior.",
      ),
      anchoTransporte: conf(1730, "ficha-pdf"),
      longitudTransporte: conf(2670, "ficha-pdf"),
      alturaTransporte: est(1830,
        "ficha-pdf",
        "1,83 m con las barandillas replegadas; 2,45 m con las barandillas montadas.",
      ),
      extensionPlataforma: conf(1.1, "ficha-pdf"),
      radioGiroInterior: conf(1.52, "ficha-pdf"),
      pendienteSuperable: conf(30, "ficha-pdf"),
      peso: est(
        3771,
        "ficha-pdf",
        "Configuración CE diésel 4x4 con neumáticos rellenos de espuma; los estabilizadores suman 483 kg.",
      ),
      velocidadTraslacion: est(
        6.1,
        "ficha-pdf",
        "6,1 km/h replegada; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf(
        "Kubota D-1105 diésel 24,9 CV; opciones Kubota gasolina/GLP 23 CV y Perkins 403D-11 diésel 26 CV",
        "ficha-pdf",
      ),
    },
    descripcionCorta:
      "Tijera diésel 4x4 de 11,75 m, la todoterreno más versátil para obra y fachada.",
    aplicaciones: [
      "Rehabilitación y limpieza de fachadas",
      "Obra civil y montajes en exterior",
      "Mantenimiento de naves y cubiertas por fuera",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs3268rt,
    trabajos: ["altura"],
    notaAsesor:
      "Es la RT que más se alquila: cubre la mayoría de fachadas de tres plantas sin montar andamio.",
  },

  /* ==========================================================
     Genie RT grandes (ficha GS-3390RT/4390RT/5390RT)
     ========================================================== */
  {
    id: "genie-gs3390rt",
    slug: "genie-gs-3390rt",
    modelo: "GS-3390RT",
    marca: "Genie",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-diesel",
    lineas: ["alquiler"],
    destacada: false,
    orden: 220,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(12.1, "ficha-pdf"),
      alturaPlataforma: conf(10.1, "ficha-pdf"),
      capacidadCarga: conf(1134, "ficha-pdf"),
      personas: conf(7, "ficha-pdf"),
      anchoTransporte: est(2290,
        "ficha-pdf",
        "2,29 m con neumáticos todoterreno; 2,57 m con neumáticos de alta flotación.",
      ),
      longitudTransporte: est(3940,
        "ficha-pdf",
        "3,94 m con una extensión de plataforma; 3,98 m con doble extensión y 4,88 m con estabilizadores.",
      ),
      alturaTransporte: est(2030,
        "ficha-pdf",
        "2,03 m con las barandillas replegadas; 2,71 m con las barandillas montadas.",
      ),
      extensionPlataforma: est(
        1.52,
        "ficha-pdf",
        "1,52 m la extensión delantera y 1,22 m la trasera; +0,41 m con la opción Super Deck.",
      ),
      radioGiroInterior: conf(2.16, "ficha-pdf"),
      pendienteSuperable: conf(50, "ficha-pdf"),
      peso: est(
        5533,
        "ficha-pdf",
        "Configuración CE diésel 4x4 con neumáticos de espuma y una extensión de plataforma.",
      ),
      velocidadTraslacion: est(
        8,
        "ficha-pdf",
        "8,0 km/h replegada; 1,1 km/h con la plataforma elevada.",
      ),
      motor: conf(
        "Deutz F3L 2011 diésel de 3 cilindros, 49 CV (36 kW), refrigerado por aire; opción Ford DSG-423 gasolina/GLP 75 CV (56 kW)",
        "ficha-pdf",
      ),
    },
    descripcionCorta:
      "Tijera diésel 4x4 de 12,10 m con 1.134 kg de carga y siete operarios en plataforma.",
    aplicaciones: [
      "Montaje de estructura y cerramiento industrial",
      "Obra civil de gran superficie",
      "Trabajos de fachada con equipo y material",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs3390rt,
    trabajos: ["altura"],
    notaAsesor:
      "Más de una tonelada en cesta: cuando hay que subir material, no solo gente.",
  },
  {
    id: "genie-gs4390rt",
    slug: "genie-gs-4390rt",
    modelo: "GS-4390RT",
    marca: "Genie",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-diesel",
    lineas: ["alquiler"],
    destacada: true,
    orden: 260,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(15.11, "ficha-pdf"),
      alturaPlataforma: conf(13.11, "ficha-pdf"),
      capacidadCarga: est(
        680,
        "ficha-pdf",
        "680 kg de serie; 800 kg en opción.",
      ),
      personas: conf(7, "ficha-pdf"),
      anchoTransporte: est(2290,
        "ficha-pdf",
        "2,29 m con neumáticos todoterreno; 2,57 m con neumáticos de alta flotación.",
      ),
      longitudTransporte: est(3940,
        "ficha-pdf",
        "3,94 m con una extensión de plataforma; 3,98 m con doble extensión y 4,88 m con estabilizadores.",
      ),
      alturaTransporte: est(2250,
        "ficha-pdf",
        "2,25 m con las barandillas replegadas; 2,93 m con las barandillas montadas.",
      ),
      extensionPlataforma: est(
        1.52,
        "ficha-pdf",
        "1,52 m la extensión delantera y 1,22 m la trasera; +0,41 m con la opción Super Deck.",
      ),
      radioGiroInterior: conf(2.16, "ficha-pdf"),
      pendienteSuperable: conf(50, "ficha-pdf"),
      peso: est(
        5949,
        "ficha-pdf",
        "Configuración CE diésel 4x4 con neumáticos de espuma y una extensión de plataforma.",
      ),
      velocidadTraslacion: est(
        8,
        "ficha-pdf",
        "8,0 km/h replegada; 1,1 km/h con la plataforma elevada.",
      ),
      motor: conf(
        "Deutz F3L 2011 diésel de 3 cilindros, 49 CV (36 kW), refrigerado por aire; opción Ford DSG-423 gasolina/GLP 75 CV (56 kW)",
        "ficha-pdf",
      ),
    },
    descripcionCorta:
      "Tijera diésel 4x4 de 15,11 m con siete operarios en plataforma y 50 % de pendiente superable.",
    aplicaciones: [
      "Montaje de estructura metálica y cubiertas",
      "Rehabilitación de fachadas altas",
      "Obra civil e industrial en exterior",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs3390rt,
    trabajos: ["altura"],
    notaAsesor:
      "A partir de aquí necesitas góndola para moverla: cuenta el transporte en el presupuesto.",
  },
  {
    id: "genie-gs5390rt",
    slug: "genie-gs-5390rt",
    modelo: "GS-5390RT",
    marca: "Genie",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-diesel",
    lineas: ["alquiler"],
    destacada: false,
    orden: 280,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(18.15, "ficha-pdf"),
      alturaPlataforma: conf(16.15, "ficha-pdf"),
      capacidadCarga: est(
        680,
        "ficha-pdf",
        "680 kg de serie; 800 kg en opción.",
      ),
      personas: conf(4, "ficha-pdf"),
      anchoTransporte: est(2290,
        "ficha-pdf",
        "2,29 m con neumáticos todoterreno; 2,57 m con neumáticos de alta flotación.",
      ),
      longitudTransporte: est(4880,
        "ficha-pdf",
        "La ficha solo publica 4,88 m con estabilizadores; las demás configuraciones figuran como no disponibles en este modelo.",
      ),
      alturaTransporte: est(2470,
        "ficha-pdf",
        "2,47 m con las barandillas replegadas; 3,15 m con las barandillas montadas.",
      ),
      extensionPlataforma: est(
        1.52,
        "ficha-pdf",
        "1,52 m la extensión delantera y 1,22 m la trasera; +0,41 m con la opción Super Deck.",
      ),
      radioGiroInterior: conf(2.16, "ficha-pdf"),
      pendienteSuperable: conf(40, "ficha-pdf"),
      peso: est(
        7615,
        "ficha-pdf",
        "Configuración CE diésel 4x4 con neumáticos de espuma; el modelo base incorpora ya los estabilizadores.",
      ),
      velocidadTraslacion: est(
        8,
        "ficha-pdf",
        "8,0 km/h replegada; 1,1 km/h con la plataforma elevada.",
      ),
      motor: conf(
        "Deutz F3L 2011 diésel de 3 cilindros, 49 CV (36 kW), refrigerado por aire; opción Ford DSG-423 gasolina/GLP 75 CV (56 kW)",
        "ficha-pdf",
      ),
    },
    descripcionCorta:
      "La tijera más alta del catálogo: 18,15 m de altura de trabajo, diésel 4x4 con estabilizadores.",
    aplicaciones: [
      "Montaje de naves y estructura de gran altura",
      "Mantenimiento de puentes grúa y cubiertas industriales",
      "Trabajos de fachada en edificios altos",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs3390rt,
    trabajos: ["altura"],
    notaAsesor:
      "Confirma el acceso y la superficie de apoyo antes de cerrar: pesa siete toneladas y media.",
  },

  /* ==========================================================
     JLG serie ES — eléctricas
     (fichero servido como haulotte-2030-3246es.pdf; el documento es de JLG)
     ========================================================== */
  {
    id: "jlg-1930es",
    slug: "jlg-1930es",
    modelo: "1930ES",
    marca: "JLG",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 50,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: est(
        7.72,
        "ficha-pdf",
        "La ficha solo publica la altura de plataforma (5,72 m); la altura de trabajo es esa más los 2 m de convención EN 280.",
      ),
      alturaPlataforma: conf(5.72, "ficha-pdf"),
      capacidadCarga: conf(230, "ficha-pdf"),
      personas: est(
        1,
        "ficha-pdf",
        "Máximo 2 personas en interior; en exterior 1 persona y 120 kg.",
      ),
      anchoTransporte: conf(760, "ficha-pdf"),
      longitudTransporte: conf(1870, "ficha-pdf"),
      alturaTransporte: est(1980,
        "ficha-pdf",
        "Altura total publicada. La ficha advierte de que las barandillas abatibles no están disponibles en este modelo.",
      ),
      extensionPlataforma: conf(0.9, "ficha-pdf"),
      radioGiroInterior: conf(0, "ficha-pdf"),
      pendienteSuperable: conf(25, "ficha-pdf"),
      peso: conf(1565, "ficha-pdf"),
      velocidadTraslacion: est(
        4.8,
        "ficha-pdf",
        "4,8 km/h recogida; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf(
        "Eléctrico 24 V: tracción de 6 kW y motor de bomba de 3 kW (4 baterías de 6 V y 220 Ah)",
        "ficha-pdf",
      ),
    },
    descripcionCorta:
      "Tijera eléctrica compacta de 5,72 m de altura de plataforma y 0,76 m de ancho.",
    aplicaciones: [
      "Mantenimiento en locales comerciales y oficinas",
      "Instalaciones eléctricas y de comunicaciones",
      "Reposición y limpieza en almacén",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.jlgEs,
    trabajos: ["altura"],
    notaAsesor:
      "Sin barandillas abatibles: mide la puerta, necesita casi dos metros de paso libre.",
  },
  {
    id: "jlg-2030es",
    slug: "jlg-2030es",
    modelo: "2030ES",
    marca: "JLG",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 70,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: est(
        8.1,
        "ficha-pdf",
        "La ficha solo publica la altura de plataforma (6,10 m); la altura de trabajo es esa más los 2 m de convención EN 280.",
      ),
      alturaPlataforma: conf(6.1, "ficha-pdf"),
      capacidadCarga: conf(360, "ficha-pdf"),
      personas: est(
        1,
        "ficha-pdf",
        "Máximo 2 personas en interior; en exterior 1 persona y 160 kg.",
      ),
      anchoTransporte: conf(760, "ficha-pdf"),
      longitudTransporte: conf(2300, "ficha-pdf"),
      alturaTransporte: conf(1810, "ficha-pdf"),
      extensionPlataforma: conf(0.9, "ficha-pdf"),
      radioGiroInterior: conf(0, "ficha-pdf"),
      pendienteSuperable: conf(25, "ficha-pdf"),
      peso: conf(2020, "ficha-pdf"),
      velocidadTraslacion: est(
        4.4,
        "ficha-pdf",
        "4,4 km/h recogida; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf(
        "Eléctrico 24 V: tracción de 6 kW y motor de bomba de 3 kW (4 baterías de 6 V y 220 Ah)",
        "ficha-pdf",
      ),
    },
    descripcionCorta:
      "Tijera eléctrica estrecha de 6,10 m de plataforma y 360 kg de carga.",
    aplicaciones: [
      "Montaje de instalaciones con material a bordo",
      "Mantenimiento en nave y almacén",
      "Trabajos de climatización y electricidad",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.jlgEs,
    trabajos: ["altura"],
    notaAsesor:
      "1,81 m de alto plegada: de las pocas que entran en un sótano o en un aparcamiento.",
  },
  {
    id: "jlg-2630es",
    slug: "jlg-2630es",
    modelo: "2630ES",
    marca: "JLG",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 100,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: est(
        9.75,
        "ficha-pdf",
        "La ficha solo publica la altura de plataforma (7,75 m); la altura de trabajo es esa más los 2 m de convención EN 280.",
      ),
      alturaPlataforma: conf(7.75, "ficha-pdf"),
      capacidadCarga: conf(230, "ficha-pdf"),
      personas: est(
        2,
        "ficha-pdf",
        "Máximo 2 personas en interior. La ficha no publica capacidad en exterior para este modelo.",
      ),
      anchoTransporte: conf(760, "ficha-pdf"),
      longitudTransporte: conf(2300, "ficha-pdf"),
      alturaTransporte: conf(1940, "ficha-pdf"),
      extensionPlataforma: conf(0.9, "ficha-pdf"),
      radioGiroInterior: conf(0, "ficha-pdf"),
      pendienteSuperable: conf(25, "ficha-pdf"),
      peso: conf(2155, "ficha-pdf"),
      velocidadTraslacion: est(
        4.4,
        "ficha-pdf",
        "4,4 km/h recogida; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf(
        "Eléctrico 24 V: tracción de 6 kW y motor de bomba de 3 kW (4 baterías de 6 V y 220 Ah)",
        "ficha-pdf",
      ),
    },
    descripcionCorta:
      "Tijera eléctrica estrecha de 7,75 m de altura de plataforma para trabajo en nave.",
    aplicaciones: [
      "Mantenimiento de luminarias y cubiertas en nave",
      "Instalación de detección y protección contra incendios",
      "Trabajos en pasillos de almacén",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.jlgEs,
    trabajos: ["altura"],
    notaAsesor:
      "La ficha no da capacidad en exterior para este modelo: si el trabajo es fuera, confírmalo antes.",
  },
  {
    id: "jlg-2646es",
    slug: "jlg-2646es",
    modelo: "2646ES",
    marca: "JLG",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 120,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: est(
        9.92,
        "ficha-pdf",
        "La ficha solo publica la altura de plataforma (7,92 m); la altura de trabajo es esa más los 2 m de convención EN 280.",
      ),
      alturaPlataforma: conf(7.92, "ficha-pdf"),
      capacidadCarga: conf(450, "ficha-pdf"),
      personas: est(
        2,
        "ficha-pdf",
        "Máximo 2 personas en interior; en exterior 2 personas y 230 kg.",
      ),
      anchoTransporte: conf(1170, "ficha-pdf"),
      longitudTransporte: conf(2500, "ficha-pdf"),
      alturaTransporte: conf(1940, "ficha-pdf"),
      extensionPlataforma: conf(1.27, "ficha-pdf"),
      radioGiroInterior: conf(0, "ficha-pdf"),
      pendienteSuperable: conf(25, "ficha-pdf"),
      peso: conf(2550, "ficha-pdf"),
      velocidadTraslacion: est(
        4,
        "ficha-pdf",
        "4,0 km/h recogida; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf(
        "Eléctrico 24 V: tracción de 6 kW y motor de bomba de 3 kW (4 baterías de 6 V y 220 Ah)",
        "ficha-pdf",
      ),
    },
    descripcionCorta:
      "Tijera eléctrica de cesta ancha, 7,92 m de plataforma y 450 kg de carga.",
    aplicaciones: [
      "Montajes industriales con dos operarios y material",
      "Mantenimiento de instalaciones en nave",
      "Montaje de estructuras y escenarios en interior",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.jlgEs,
    trabajos: ["altura"],
    notaAsesor:
      "Cuando hacen falta dos personas trabajando a la vez, esta cesta es la que da sitio.",
  },
  {
    id: "jlg-3246es",
    slug: "jlg-3246es",
    modelo: "3246ES",
    marca: "JLG",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 170,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: est(
        11.68,
        "ficha-pdf",
        "La ficha solo publica la altura de plataforma (9,68 m); la altura de trabajo es esa más los 2 m de convención EN 280.",
      ),
      alturaPlataforma: conf(9.68, "ficha-pdf"),
      capacidadCarga: conf(320, "ficha-pdf"),
      personas: est(
        1,
        "ficha-pdf",
        "Máximo 2 personas en interior; en exterior 1 persona y 320 kg.",
      ),
      anchoTransporte: conf(1170, "ficha-pdf"),
      longitudTransporte: conf(2500, "ficha-pdf"),
      alturaTransporte: conf(1940, "ficha-pdf"),
      extensionPlataforma: conf(1.27, "ficha-pdf"),
      radioGiroInterior: conf(0, "ficha-pdf"),
      pendienteSuperable: conf(25, "ficha-pdf"),
      peso: conf(2725, "ficha-pdf"),
      velocidadTraslacion: est(
        4,
        "ficha-pdf",
        "4,0 km/h recogida; 0,8 km/h con la plataforma elevada.",
      ),
      motor: conf(
        "Eléctrico 24 V: tracción de 6 kW y motor de bomba de 3 kW (4 baterías de 6 V y 220 Ah)",
        "ficha-pdf",
      ),
    },
    descripcionCorta:
      "Tijera eléctrica de 9,68 m de altura de plataforma con cesta ancha y extensión de 1,27 m.",
    aplicaciones: [
      "Mantenimiento bajo cubierta en naves altas",
      "Instalación de iluminación y climatización",
      "Montajes en pabellones y salas diáfanas",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.jlgEs,
    trabajos: ["altura"],
    notaAsesor:
      "Casi doce metros de trabajo sin motor de combustión: la opción limpia para interiores altos.",
  },

  /* ==========================================================
     JLG RT diésel
     (fichero servido como genie-gs-3394rt.pdf; el documento es de JLG)
     ========================================================== */
  {
    id: "jlg-3394rt",
    slug: "jlg-3394rt",
    modelo: "3394RT",
    marca: "JLG",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-diesel",
    lineas: ["alquiler"],
    destacada: false,
    orden: 210,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: est(
        12.05,
        "ficha-pdf",
        "La ficha solo publica la altura de plataforma (10,05 m); la altura de trabajo es esa más los 2 m de convención EN 280.",
      ),
      alturaPlataforma: conf(10.05, "ficha-pdf"),
      capacidadCarga: est(
        1020,
        "ficha-pdf",
        "1.020 kg de capacidad; 905 kg con el desplazable opcional montado y 225 kg sobre el propio desplazable.",
      ),
      personas: pend<number>(
        "La ficha de JLG no publica el número máximo de personas en plataforma.",
      ),
      anchoTransporte: conf(2390, "ficha-pdf"),
      longitudTransporte: est(3810,
        "ficha-pdf",
        "Longitud total publicada; con los soportes de compensación opcionales pasa a 4,75 m.",
      ),
      alturaTransporte: conf(1970, "ficha-pdf"),
      extensionPlataforma: est(
        1.22,
        "ficha-pdf",
        "Desplazable lateral de 1,22 m, disponible en frontal y trasero.",
      ),
      radioGiroInterior: conf(2.71, "ficha-pdf"),
      pendienteSuperable: est(
        45,
        "ficha-pdf",
        "45 % en configuración 4x4x2; la ficha no publica valor para la 4x2x2.",
      ),
      peso: conf(5850, "ficha-pdf"),
      velocidadTraslacion: est(
        6.4,
        "ficha-pdf",
        "6,4 km/h en configuración 4x4x2; la ficha no publica valor para la 4x2x2.",
      ),
      motor: conf("Deutz F3M1011F diésel de 34 kW", "ficha-pdf"),
    },
    descripcionCorta:
      "Tijera diésel todoterreno de 10,05 m de plataforma y 1.020 kg de carga.",
    aplicaciones: [
      "Montaje de estructura y cerramientos en obra",
      "Trabajos de fachada con material a bordo",
      "Mantenimiento de instalaciones exteriores",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs3394rt,
    trabajos: ["altura"],
    notaAsesor:
      "Una tonelada en cesta y eje oscilante: para obra en bruto es más práctica que cualquier eléctrica.",
  },
  {
    id: "jlg-4394rt",
    slug: "jlg-4394rt",
    modelo: "4394RT",
    marca: "JLG",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-diesel",
    lineas: ["alquiler"],
    destacada: false,
    orden: 250,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: est(
        15.1,
        "ficha-pdf",
        "La ficha solo publica la altura de plataforma (13,10 m); la altura de trabajo es esa más los 2 m de convención EN 280.",
      ),
      alturaPlataforma: conf(13.1, "ficha-pdf"),
      capacidadCarga: est(
        680,
        "ficha-pdf",
        "680 kg de capacidad; 565 kg con el desplazable opcional montado y 225 kg sobre el propio desplazable.",
      ),
      personas: pend<number>(
        "La ficha de JLG no publica el número máximo de personas en plataforma.",
      ),
      anchoTransporte: conf(2390, "ficha-pdf"),
      longitudTransporte: est(3810,
        "ficha-pdf",
        "Longitud total publicada; con los soportes de compensación opcionales pasa a 4,75 m.",
      ),
      alturaTransporte: conf(2190, "ficha-pdf"),
      extensionPlataforma: est(
        1.22,
        "ficha-pdf",
        "Desplazable lateral de 1,22 m, disponible en frontal y trasero.",
      ),
      radioGiroInterior: conf(2.71, "ficha-pdf"),
      pendienteSuperable: est(
        45,
        "ficha-pdf",
        "45 % en configuración 4x4x2; la ficha no publica valor para la 4x2x2.",
      ),
      peso: conf(6900, "ficha-pdf"),
      velocidadTraslacion: est(
        6.4,
        "ficha-pdf",
        "6,4 km/h en configuración 4x4x2; la ficha no publica valor para la 4x2x2.",
      ),
      motor: conf("Deutz F3M1011F diésel de 34 kW", "ficha-pdf"),
    },
    descripcionCorta:
      "Tijera diésel todoterreno de 13,10 m de altura de plataforma y 680 kg de carga.",
    aplicaciones: [
      "Montaje de estructura metálica y cubiertas",
      "Rehabilitación de fachadas de varias plantas",
      "Obra civil e industrial en exterior",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.gs3394rt,
    trabajos: ["altura"],
    notaAsesor:
      "Se puede trasladar con la plataforma arriba: para trabajos largos de fachada ahorra mucho tiempo.",
  },

  /* ==========================================================
     Haulotte Compact — eléctricas
     ========================================================== */
  {
    id: "haulotte-compact8",
    slug: "haulotte-compact-8",
    modelo: "Compact 8",
    marca: "Haulotte",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 80,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(8.18, "ficha-pdf"),
      alturaPlataforma: conf(6.18, "ficha-pdf"),
      capacidadCarga: conf(350, "ficha-pdf"),
      personas: pend<number>(
        "La ficha de Haulotte no publica el número de personas en plataforma, solo la capacidad en kg.",
      ),
      anchoTransporte: conf(810, "ficha-pdf"),
      longitudTransporte: est(2310,
        "ficha-pdf",
        "2,31 m replegada; 2,48 m con la extensión de plataforma desplegada.",
      ),
      alturaTransporte: est(1990,
        "ficha-pdf",
        "1,99 m medidos con las barandillas; 1,14 m hasta el suelo de la plataforma.",
      ),
      extensionPlataforma: conf(0.92, "ficha-pdf"),
      radioGiroInterior: conf(0.34, "ficha-pdf"),
      pendienteSuperable: conf(25, "ficha-pdf"),
      peso: conf(1730, "ficha-pdf"),
      velocidadTraslacion: est(
        3.5,
        "ficha-pdf",
        "Dos velocidades de traslación: 1 km/h y 3,5 km/h.",
      ),
      motor: conf(
        "Eléctrico 24 V (4 baterías de 6 V), 180 Ah, con cargador de 30 A",
        "ficha-pdf",
      ),
    },
    descripcionCorta:
      "Tijera eléctrica estrecha de 8,18 m de altura de trabajo y 350 kg de carga.",
    aplicaciones: [
      "Mantenimiento en locales y oficinas",
      "Instalaciones eléctricas y de climatización",
      "Trabajos en pasillos y zonas de acceso difícil",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.compact,
    trabajos: ["altura"],
    notaAsesor:
      "1,99 m plegada: es la que suele entrar por la puerta de un local sin desmontar nada.",
  },
  {
    id: "haulotte-compact10n",
    slug: "haulotte-compact-10-n",
    modelo: "Compact 10 N",
    marca: "Haulotte",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 140,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(10, "ficha-pdf"),
      alturaPlataforma: conf(8, "ficha-pdf"),
      capacidadCarga: conf(230, "ficha-pdf"),
      personas: pend<number>(
        "La ficha de Haulotte no publica el número de personas en plataforma, solo la capacidad en kg.",
      ),
      anchoTransporte: conf(810, "ficha-pdf"),
      longitudTransporte: est(2310,
        "ficha-pdf",
        "2,31 m replegada; 2,48 m con la extensión de plataforma desplegada.",
      ),
      alturaTransporte: est(2180,
        "ficha-pdf",
        "2,18 m medidos con las barandillas; 1,33 m hasta el suelo de la plataforma.",
      ),
      extensionPlataforma: conf(0.92, "ficha-pdf"),
      radioGiroInterior: conf(0.34, "ficha-pdf"),
      pendienteSuperable: conf(23, "ficha-pdf"),
      peso: conf(2160, "ficha-pdf"),
      velocidadTraslacion: est(
        3.5,
        "ficha-pdf",
        "Dos velocidades de traslación: 1 km/h y 3,5 km/h.",
      ),
      motor: conf(
        "Eléctrico 24 V (4 baterías de 6 V), 180 Ah, con cargador de 30 A",
        "ficha-pdf",
      ),
    },
    descripcionCorta:
      "Tijera eléctrica estrecha de 10 m de altura de trabajo, con barandillas abatibles.",
    aplicaciones: [
      "Mantenimiento de luminarias y cubiertas en nave",
      "Instalación de conductos e instalaciones bajo techo",
      "Montajes en interior con acceso estrecho",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.compact,
    trabajos: ["altura"],
    notaAsesor:
      "Diez metros con 81 cm de ancho: la típica para naves con pasillos estrechos.",
  },
  {
    id: "haulotte-compact8w",
    slug: "haulotte-compact-8w",
    modelo: "Compact 8W",
    marca: "Haulotte",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 90,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(8.27, "ficha-pdf"),
      alturaPlataforma: conf(6.27, "ficha-pdf"),
      capacidadCarga: conf(450, "ficha-pdf"),
      personas: pend<number>(
        "La ficha de Haulotte no publica el número de personas en plataforma, solo la capacidad en kg.",
      ),
      anchoTransporte: conf(1200, "ficha-pdf"),
      longitudTransporte: est(2310,
        "ficha-pdf",
        "2,31 m replegada; 2,46 m con la extensión de plataforma desplegada.",
      ),
      alturaTransporte: est(2140,
        "ficha-pdf",
        "2,14 m medidos con las barandillas; 1,02 m hasta el suelo de la plataforma.",
      ),
      extensionPlataforma: conf(0.92, "ficha-pdf"),
      radioGiroInterior: conf(0.2, "ficha-pdf"),
      pendienteSuperable: conf(23, "ficha-pdf"),
      peso: conf(1950, "ficha-pdf"),
      velocidadTraslacion: est(
        3,
        "ficha-pdf",
        "Dos velocidades de traslación: 1 km/h y 3 km/h.",
      ),
      motor: est(
        "Eléctrico 24 V (4 baterías de 6 V), con cargador de 30 A",
        "ficha-pdf",
        "La ficha da 250 Ah C5 en la tabla y 240 Ah en el listado de equipamiento estándar; no se transcribe la capacidad hasta confirmarla.",
      ),
    },
    descripcionCorta:
      "Tijera eléctrica de cesta ancha, 8,27 m de altura de trabajo y 450 kg de carga.",
    aplicaciones: [
      "Montaje de instalaciones con material voluminoso",
      "Mantenimiento industrial en nave",
      "Trabajos con dos operarios y herramienta",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.compact,
    trabajos: ["altura"],
    notaAsesor:
      "450 kg de cesta con motor eléctrico: la más práctica para montajes en interior.",
  },
  {
    id: "haulotte-compact10",
    slug: "haulotte-compact-10",
    modelo: "Compact 10",
    marca: "Haulotte",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 150,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(10.14, "ficha-pdf"),
      alturaPlataforma: conf(8.14, "ficha-pdf"),
      capacidadCarga: conf(450, "ficha-pdf"),
      personas: pend<number>(
        "La ficha de Haulotte no publica el número de personas en plataforma, solo la capacidad en kg.",
      ),
      anchoTransporte: conf(1200, "ficha-pdf"),
      longitudTransporte: est(2310,
        "ficha-pdf",
        "2,31 m replegada; 2,46 m con la extensión de plataforma desplegada.",
      ),
      alturaTransporte: est(2260,
        "ficha-pdf",
        "2,26 m medidos con las barandillas; 1,14 m hasta el suelo de la plataforma.",
      ),
      extensionPlataforma: conf(0.92, "ficha-pdf"),
      radioGiroInterior: conf(0.2, "ficha-pdf"),
      pendienteSuperable: conf(23, "ficha-pdf"),
      peso: conf(2330, "ficha-pdf"),
      velocidadTraslacion: est(
        3,
        "ficha-pdf",
        "Dos velocidades de traslación: 1 km/h y 3 km/h.",
      ),
      motor: est(
        "Eléctrico 24 V (4 baterías de 6 V), con cargador de 30 A",
        "ficha-pdf",
        "La ficha da 250 Ah C5 en la tabla y 240 Ah en el listado de equipamiento estándar; no se transcribe la capacidad hasta confirmarla.",
      ),
    },
    descripcionCorta:
      "Tijera eléctrica de cesta ancha con 10,14 m de altura de trabajo y 450 kg de carga.",
    aplicaciones: [
      "Mantenimiento de instalaciones bajo cubierta",
      "Montaje de conductos, bandejas e iluminación",
      "Montajes de escenografía y estructuras en interior",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.compact,
    trabajos: ["altura"],
    notaAsesor:
      "Ojo con la Compact 10 N: se parece en nombre pero es más estrecha y solo lleva 230 kg.",
  },
  {
    id: "haulotte-compact12",
    slug: "haulotte-compact-12",
    modelo: "Compact 12",
    marca: "Haulotte",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 190,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(12, "ficha-pdf"),
      alturaPlataforma: conf(10, "ficha-pdf"),
      capacidadCarga: conf(300, "ficha-pdf"),
      personas: pend<number>(
        "La ficha de Haulotte no publica el número de personas en plataforma, solo la capacidad en kg.",
      ),
      anchoTransporte: conf(1200, "ficha-pdf"),
      longitudTransporte: est(2310,
        "ficha-pdf",
        "2,31 m replegada; 2,46 m con la extensión de plataforma desplegada.",
      ),
      alturaTransporte: est(2380,
        "ficha-pdf",
        "2,38 m medidos con las barandillas; 1,26 m hasta el suelo de la plataforma.",
      ),
      extensionPlataforma: conf(0.92, "ficha-pdf"),
      radioGiroInterior: conf(0.2, "ficha-pdf"),
      pendienteSuperable: conf(23, "ficha-pdf"),
      peso: conf(2630, "ficha-pdf"),
      velocidadTraslacion: est(
        3,
        "ficha-pdf",
        "Dos velocidades de traslación: 1 km/h y 3 km/h.",
      ),
      motor: est(
        "Eléctrico 24 V (4 baterías de 6 V), con cargador de 30 A",
        "ficha-pdf",
        "La ficha da 250 Ah C5 en la tabla y 240 Ah en el listado de equipamiento estándar; no se transcribe la capacidad hasta confirmarla.",
      ),
    },
    descripcionCorta:
      "Tijera eléctrica de 12 m de altura de trabajo y 1,20 m de ancho.",
    aplicaciones: [
      "Mantenimiento en naves de gran altura",
      "Instalación de iluminación y protección contra incendios",
      "Montajes en pabellones y recintos cubiertos",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.compact,
    trabajos: ["altura"],
    notaAsesor:
      "Doce metros sin humos ni ruido: la alternativa a la diésel cuando el trabajo es dentro.",
  },

  /* ==========================================================
     Haulotte H SX — tijeras diésel todoterreno
     ========================================================== */
  {
    id: "haulotte-h12sx",
    slug: "haulotte-h12sx",
    modelo: "H12SX",
    marca: "Haulotte",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-diesel",
    lineas: ["alquiler"],
    destacada: false,
    orden: 200,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(12, "ficha-pdf"),
      alturaPlataforma: conf(10, "ficha-pdf"),
      capacidadCarga: est(
        700,
        "ficha-pdf",
        "Capacidad máxima publicada con las dos extensiones; 200 kg sobre la extensión.",
      ),
      personas: pend<number>(
        "La ficha de Haulotte no publica el número de personas en plataforma, solo la capacidad en kg.",
      ),
      anchoTransporte: conf(2250, "ficha-pdf"),
      longitudTransporte: conf(4180, "ficha-pdf"),
      alturaTransporte: est(1710,
        "ficha-pdf",
        "1,71 m en posición de transporte; 2,57 m replegada con las barandillas montadas.",
      ),
      extensionPlataforma: est(
        1,
        "ficha-pdf",
        "Extensión de 1 m; el equipamiento estándar incluye doble extensión de 1 m.",
      ),
      radioGiroInterior: pend<number>(
        "La ficha solo publica el radio de giro exterior (5,90 m).",
      ),
      pendienteSuperable: conf(40, "ficha-pdf"),
      peso: conf(5510, "ficha-pdf"),
      velocidadTraslacion: est(
        6,
        "ficha-pdf",
        "Dos velocidades de traslación: 1,6 km/h y 6 km/h.",
      ),
      motor: conf("Diésel de 32 CV (24 kW)", "ficha-pdf"),
    },
    descripcionCorta:
      "Tijera diésel 4x4 de 12 m con doble extensión de plataforma y estabilizadores.",
    aplicaciones: [
      "Trabajos de fachada y cerramiento",
      "Obra civil y urbanización",
      "Mantenimiento de instalaciones exteriores",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.hsx,
    trabajos: ["altura"],
    notaAsesor:
      "Con la doble extensión cubres seis metros de fachada sin mover la máquina.",
  },
  {
    id: "haulotte-h15sx",
    slug: "haulotte-h15sx",
    modelo: "H15SX",
    marca: "Haulotte",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-diesel",
    lineas: ["alquiler"],
    destacada: false,
    orden: 240,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(15, "ficha-pdf"),
      alturaPlataforma: conf(13, "ficha-pdf"),
      capacidadCarga: est(
        500,
        "ficha-pdf",
        "Capacidad máxima publicada con las dos extensiones; 200 kg sobre la extensión.",
      ),
      personas: pend<number>(
        "La ficha de Haulotte no publica el número de personas en plataforma, solo la capacidad en kg.",
      ),
      anchoTransporte: conf(2250, "ficha-pdf"),
      longitudTransporte: conf(4180, "ficha-pdf"),
      alturaTransporte: est(1900,
        "ficha-pdf",
        "1,90 m en posición de transporte; 2,77 m replegada con las barandillas montadas.",
      ),
      extensionPlataforma: est(
        1,
        "ficha-pdf",
        "Extensión de 1 m; el equipamiento estándar incluye doble extensión de 1 m.",
      ),
      radioGiroInterior: pend<number>(
        "La ficha solo publica el radio de giro exterior (5,90 m).",
      ),
      pendienteSuperable: conf(40, "ficha-pdf"),
      peso: conf(6340, "ficha-pdf"),
      velocidadTraslacion: est(
        6,
        "ficha-pdf",
        "Dos velocidades de traslación: 1,6 km/h y 6 km/h.",
      ),
      motor: conf("Diésel de 32 CV (24 kW)", "ficha-pdf"),
    },
    descripcionCorta:
      "Tijera diésel 4x4 de 15 m de altura de trabajo con doble extensión de plataforma.",
    aplicaciones: [
      "Rehabilitación de fachadas de varias plantas",
      "Montaje de estructura y cubiertas en obra",
      "Mantenimiento industrial en exterior",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.hsx,
    trabajos: ["altura"],
    notaAsesor:
      "Si el suelo tiene desnivel, esta se calza sola con los estabilizadores.",
  },
  {
    id: "haulotte-h18sx",
    slug: "haulotte-h18sx",
    modelo: "H18SX",
    marca: "Haulotte",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-diesel",
    lineas: ["alquiler"],
    destacada: false,
    orden: 270,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: [...TODAS],
    specs: {
      ...NO_APLICA_EN_TIJERA,
      alturaTrabajo: conf(18, "ficha-pdf"),
      alturaPlataforma: conf(16, "ficha-pdf"),
      capacidadCarga: est(
        500,
        "ficha-pdf",
        "Capacidad máxima publicada con las dos extensiones; 200 kg sobre la extensión.",
      ),
      personas: pend<number>(
        "La ficha de Haulotte no publica el número de personas en plataforma, solo la capacidad en kg.",
      ),
      anchoTransporte: conf(2250, "ficha-pdf"),
      longitudTransporte: conf(4180, "ficha-pdf"),
      alturaTransporte: est(2110,
        "ficha-pdf",
        "2,11 m en posición de transporte; 2,96 m replegada con las barandillas montadas.",
      ),
      extensionPlataforma: est(
        1,
        "ficha-pdf",
        "Extensión de 1 m; el equipamiento estándar incluye doble extensión de 1 m.",
      ),
      radioGiroInterior: pend<number>(
        "La ficha solo publica el radio de giro exterior (5,90 m).",
      ),
      pendienteSuperable: conf(40, "ficha-pdf"),
      peso: conf(7300, "ficha-pdf"),
      velocidadTraslacion: est(
        6,
        "ficha-pdf",
        "Dos velocidades de traslación: 1,6 km/h y 6 km/h.",
      ),
      motor: conf("Diésel de 32 CV (24 kW)", "ficha-pdf"),
    },
    descripcionCorta:
      "Tijera diésel 4x4 de 18 m, la Haulotte todoterreno de mayor altura del catálogo.",
    aplicaciones: [
      "Montaje de estructura metálica de gran altura",
      "Trabajos de fachada en edificios altos",
      "Obra civil e industrial en exterior",
    ],
    destacados: [],
    imagenes: [],
    fichaTecnica: FICHA.hsx,
    trabajos: ["altura"],
    notaAsesor:
      "A 18 m de altura el viento manda: comprueba el límite del manual antes de programar el trabajo.",
  },
];
