/* GENERADO por scripts/convertir-catalogo.mjs — no editar a mano.
 *
 * Especificaciones de catálogo de fabricante. Entran como "estimado"
 * a propósito: son cifras publicadas por Genie, JLG, Haulotte, Manitou,
 * Takeuchi, Jungheinrich y compañía, pero nadie de JOFEMESA las ha
 * confirmado todavía contra la unidad concreta que tiene en el parque.
 *
 * La interfaz las muestra con su marca de "dato de fabricante" y el
 * comercial las confirma al responder la solicitud. Las verificadas
 * contra la ficha técnica real viven en maquinas-verificadas.ts.
 */
import type { Maquina } from "./types";
import { est } from "./types";

export const MAQUINAS_CATALOGO: Maquina[] = [
  {
    id: "genie-gr-12",
    slug: "genie-runabout-gr-12",
    marca: "Genie",
    modelo: "Runabout GR-12",
    familia: "elevacion",
    subcategoriaSlug: "mastiles-verticales",
    lineas: ["alquiler"],
    destacada: false,
    orden: 10,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(5.45),
      capacidadCarga: est(227),
      anchoTransporte: est(750),
      alturaTransporte: est(1980),
      longitudTransporte: est(1350),
      peso: est(717),
      dimensionesPlataforma: est("0.89 x 0.75 m"),
      traccion: est("2x4"),
    },
    descripcionCorta: "Mástil vertical ultracompacto para tareas de mantenimiento e instalación en interiores. Pasa fácilmente por puertas estándar y entra en la mayoría de montacargas sin dejar marcas en el suelo.",
    aplicaciones: ["Mantenimiento de techos y luminarias", "Centros comerciales y oficinas", "Inventario y logística ligera"],
    destacados: ["Pasa por puertas estándar (75 cm)", "Ruedas antihuella", "Radio de giro cero"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "haulotte-star-10",
    slug: "haulotte-star-10",
    marca: "Haulotte",
    modelo: "Star 10",
    familia: "elevacion",
    subcategoriaSlug: "mastiles-verticales",
    lineas: ["alquiler"],
    destacada: false,
    orden: 20,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(10),
      alcanceHorizontal: est(3),
      capacidadCarga: est(200),
      anchoTransporte: est(1000),
      alturaTransporte: est(1990),
      longitudTransporte: est(2700),
      peso: est(2677),
      traccion: est("2x4"),
    },
    descripcionCorta: "Mástil vertical con plumín pendular de 3 metros para salvar obstáculos en altura. Excelente maniobrabilidad en pasillos estrechos de almacén y líneas de producción industrial.",
    aplicaciones: ["Mantenimiento industrial", "Salvado de estanterías y conductos", "Instalación de tuberías aéreas"],
    destacados: ["Plumín con alcance horizontal de 3 m", "Voladizo posterior cero", "Motores AC sin escobillas"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "genie-gs-1932",
    slug: "genie-gs-1932",
    marca: "Genie",
    modelo: "GS-1932",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 30,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(7.79),
      capacidadCarga: est(227),
      anchoTransporte: est(813),
      alturaTransporte: est(2110),
      longitudTransporte: est(1830),
      peso: est(1503),
      dimensionesPlataforma: est("1.63 x 0.74 m (+ extensión 0.91 m)"),
      traccion: est("2x4"),
    },
    descripcionCorta: "Tijera eléctrica compacta para trabajos de instalación y montaje en interiores. Sus 81 cm de anchura permiten el paso por puertas simples y pasillos estrechos con total estabilidad.",
    aplicaciones: ["Instalación eléctrica y climatización", "Falsos techos y pintura", "Reformas interiores"],
    destacados: ["Anchura de solo 81 cm", "Extensión de plataforma extensible", "Cero emisiones acústicas y de escape"],
    imagenes: [],
    fichaTecnica: { src: "/fichas/genie-gs-1932.pdf", bytes: 2472274 },
    trabajos: ["altura"],
  },
  {
    id: "genie-gs-3246",
    slug: "genie-gs-3246",
    marca: "Genie",
    modelo: "GS-3246",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 40,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(11.75),
      capacidadCarga: est(318),
      anchoTransporte: est(1160),
      alturaTransporte: est(2390),
      longitudTransporte: est(2410),
      peso: est(2812),
      dimensionesPlataforma: est("2.26 x 1.15 m (+ extensión 0.91 m)"),
      traccion: est("2x4"),
    },
    descripcionCorta: "Plataforma de tijera eléctrica de 12 metros con amplia cesta de trabajo y capacidad para dos operarios con herramienta pesada. Desplazamiento suave y máxima autonomía de batería.",
    aplicaciones: ["Construcción de naves industriales", "Sistemas contra incendios", "Mantenimiento de techumbres"],
    destacados: ["Gran capacidad de 318 kg", "Cesta amplia de 2.26 m", "Apta para interior y exterior plano"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "haulotte-compact-14",
    slug: "haulotte-compact-14",
    marca: "Haulotte",
    modelo: "Compact 14",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-electricas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 50,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(13.85),
      capacidadCarga: est(350),
      anchoTransporte: est(1200),
      alturaTransporte: est(2500),
      longitudTransporte: est(2480),
      peso: est(3175),
      dimensionesPlataforma: est("2.31 x 1.20 m (+ extensión 0.92 m)"),
      traccion: est("2x4"),
    },
    descripcionCorta: "Tijera eléctrica de 14 metros de altura de trabajo con excelente capacidad de carga. Diseñada para tareas que exigen elevar materiales de montaje pesado a gran altura en interior.",
    aplicaciones: ["Centros logísticos de gran altura", "Instalaciones mecánicas y conductos", "Montaje de luminarias y placas"],
    destacados: ["Carga útil elevada (350 kg)", "Traslación a máxima altura", "Protección antibaches automática"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "haulotte-compact-12-dx",
    slug: "haulotte-compact-12-dx-4x4",
    marca: "Haulotte",
    modelo: "Compact 12 DX 4x4",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-diesel",
    lineas: ["alquiler"],
    destacada: false,
    orden: 60,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(12.06),
      capacidadCarga: est(450),
      anchoTransporte: est(1780),
      alturaTransporte: est(2560),
      longitudTransporte: est(3170),
      peso: est(4060),
      pendienteSuperable: est("40%"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Tijera diésel 4x4 compacta con estabilizadores hidráulicos automáticos. Ideal para trabajos de fachada y estructuras en terrenos de obra no pavimentados con pendientes.",
    aplicaciones: ["Cerramientos de fachadas", "Estructuras metálicas exteriores", "Obras de edificación residencial"],
    destacados: ["Tracción 4x4 permanente", "Estabilizadores autonivelantes", "Carga máxima 450 kg"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "genie-gs-5390-rt",
    slug: "genie-gs-5390-rt-4x4",
    marca: "Genie",
    modelo: "GS-5390 RT 4x4",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-diesel",
    lineas: ["alquiler"],
    destacada: false,
    orden: 70,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(18.15),
      capacidadCarga: est(680),
      anchoTransporte: est(2290),
      alturaTransporte: est(3150),
      longitudTransporte: est(4880),
      peso: est(7639),
      dimensionesPlataforma: est("3.98 x 1.83 m (+ doble extensión hasta 7.38 m)"),
      pendienteSuperable: est("50%"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Gran tijera todoterreno de 18 metros con plataforma extralarga de doble extensión y capacidad para 680 kg. Permite subir equipos completos de montaje con sus materiales en un único izado.",
    aplicaciones: ["Grandes fachadas y muros cortina", "Instalación de paneles sándwich", "Obras de ingeniería civil"],
    destacados: ["Plataforma gigante extensible a 7.38 m", "Capacidad masiva de 680 kg", "Eje oscilante activo"],
    imagenes: [],
    fichaTecnica: { src: "/fichas/genie-gs-3390-4390-5390rt.pdf", bytes: 871888 },
    trabajos: ["altura"],
  },
  {
    id: "genie-gs-3369-be",
    slug: "genie-gs-3369-be-bi-energy",
    marca: "Genie",
    modelo: "GS-3369 BE Bi-Energy",
    familia: "elevacion",
    subcategoriaSlug: "tijeras-hibridas",
    lineas: ["alquiler"],
    destacada: false,
    orden: 80,
    facetas: {
      energia: "hibrido",
      entornos: ["interior", "exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(11.75),
      capacidadCarga: est(454),
      anchoTransporte: est(1750),
      alturaTransporte: est(2590),
      longitudTransporte: est(3760),
      peso: est(3975),
      traccion: est("4x4"),
    },
    descripcionCorta: "Tijera híbrida de 12 metros que combina tracción todoterreno en obra con funcionamiento 100% eléctrico libre de humos para el interior de las naves. Máxima flexibilidad operativa.",
    aplicaciones: ["Proyectos con fases mixtas exterior/interior", "Entornos con restricciones de emisiones", "Edificación sostenible"],
    destacados: ["Modo eléctrico y modo generador diésel", "Tracción todoterreno", "Capacidad 454 kg"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "haulotte-ha12-ip",
    slug: "haulotte-ha12-ip",
    marca: "Haulotte",
    modelo: "HA12 IP",
    familia: "elevacion",
    subcategoriaSlug: "brazos-articulados-electricos",
    lineas: ["alquiler"],
    destacada: false,
    orden: 90,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(12),
      alcanceHorizontal: est(6.5),
      capacidadCarga: est(230),
      anchoTransporte: est(1350),
      alturaTransporte: est(1990),
      longitudTransporte: est(5400),
      peso: est(5900),
      traccion: est("2x4"),
    },
    descripcionCorta: "Brazo articulado eléctrico de 12 metros con giro dentro del gálibo. Ideal para trabajar en zonas congestionadas de fábrica y plantas químicas con conductos aéreos.",
    aplicaciones: ["Mantenimiento en fábricas y plantas", "Instalación de tuberías industriales", "Pintura y restauración interior"],
    destacados: ["Voladizo cero", "Plumín con movimiento vertical positivo/negativo", "Anchura contenida de 1.35 m"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "genie-z-45-25j-dc",
    slug: "genie-z-45-25j-dc",
    marca: "Genie",
    modelo: "Z-45/25J DC",
    familia: "elevacion",
    subcategoriaSlug: "brazos-articulados-electricos",
    lineas: ["alquiler"],
    destacada: false,
    orden: 100,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(15.92),
      alcanceHorizontal: est(7.65),
      capacidadCarga: est(227),
      anchoTransporte: est(1790),
      alturaTransporte: est(2000),
      longitudTransporte: est(6830),
      peso: est(7394),
      traccion: est("2x4"),
    },
    descripcionCorta: "Brazo articulado eléctrico de casi 16 metros con excelente articulación de 7.24 m sobre punto de articulación. Permite posicionarse con precisión milimétrica sobre maquinaria en funcionamiento.",
    aplicaciones: ["Grandes recintos feriales y pabellones", "Mantenimiento aeronáutico y ferroviario", "Centros de distribución logística"],
    destacados: ["Articulación a 7.24 m de altura", "Plumín rotatorio 135°", "Cero emisiones"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "haulotte-ha16-rtj",
    slug: "haulotte-ha16-rtj-4x4",
    marca: "Haulotte",
    modelo: "HA16 RTJ 4x4",
    familia: "elevacion",
    subcategoriaSlug: "brazos-diesel",
    lineas: ["alquiler"],
    destacada: true,
    orden: 110,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(16),
      alcanceHorizontal: est(8.3),
      capacidadCarga: est(230),
      anchoTransporte: est(2300),
      alturaTransporte: est(2300),
      longitudTransporte: est(6750),
      peso: est(6650),
      pendienteSuperable: est("45%"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Brazo articulado diésel 4x4 de 16 metros líder en agilidad y velocidad de elevación. Supera terrenos abruptos gracias a su eje oscilante y bloqueo diferencial.",
    aplicaciones: ["Montaje de estructuras metálicas", "Poda y arbolado en exterior", "Obras de construcción y puentes"],
    destacados: ["Tiempo de elevación récord (40 s)", "Tracción 4x4 con 4 ruedas directrices", "Sistema anticolisión Haulotte Activ'Shield Bar"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "genie-z-62-40",
    slug: "genie-z-62-40-4x4",
    marca: "Genie",
    modelo: "Z-62/40 4x4",
    familia: "elevacion",
    subcategoriaSlug: "brazos-diesel",
    lineas: ["alquiler"],
    destacada: false,
    orden: 120,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(20.87),
      alcanceHorizontal: est(12.42),
      capacidadCarga: est(227),
      anchoTransporte: est(2490),
      alturaTransporte: est(2540),
      longitudTransporte: est(9250),
      peso: est(10433),
      pendienteSuperable: est("45%"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Brazo articulado diésel todoterreno de casi 21 metros con alcance horizontal de 12.4 m. Su sistema Genie Fast Mast eleva y desciende la cesta simultáneamente con máxima rapidez.",
    aplicaciones: ["Construcción pesada y obra civil", "Mantenimiento de refinerías y petroquímicas", "Montajes de gran escala"],
    destacados: ["Alcance de 12.42 m con articulación a 7.8 m", "Sistema Genie FastMast™", "Tracción 4WD con eje oscilante"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "haulotte-ha26-rtj-pro",
    slug: "haulotte-ha26-rtj-pro-4x4",
    marca: "Haulotte",
    modelo: "HA26 RTJ PRO 4x4",
    familia: "elevacion",
    subcategoriaSlug: "brazos-diesel",
    lineas: ["alquiler"],
    destacada: false,
    orden: 130,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(26.4),
      alcanceHorizontal: est(17.5),
      capacidadCarga: est(250),
      anchoTransporte: est(2480),
      alturaTransporte: est(2970),
      longitudTransporte: est(11800),
      peso: est(15500),
      pendienteSuperable: est("45%"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Brazo articulado diésel de 26.4 metros con alcance lateral de 17.5 metros y capacidad de carga de 250 kg. Tracción y dirección a las 4 ruedas para maniobrar en espacios complejos de obra.",
    aplicaciones: ["Plantas petroquímicas y energía", "Grandes estructuras de hormigón y acero", "Astilleros y puertos"],
    destacados: ["Alcance horizontal líder de 17.5 m", "4 ruedas directrices y tracción total", "Activ'Lighting System para carga nocturna"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "genie-z-45-fe",
    slug: "genie-z-45-fe-hybrid-4x4",
    marca: "Genie",
    modelo: "Z-45 FE Hybrid 4x4",
    familia: "elevacion",
    subcategoriaSlug: "brazos-hibridos",
    lineas: ["alquiler"],
    destacada: false,
    orden: 140,
    facetas: {
      energia: "hibrido",
      entornos: ["interior", "exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(15.92),
      alcanceHorizontal: est(6.94),
      capacidadCarga: est(300),
      anchoTransporte: est(2290),
      alturaTransporte: est(2290),
      longitudTransporte: est(6170),
      peso: est(6559),
      traccion: est("4x4"),
    },
    descripcionCorta: "Brazo híbrido todoterreno de 16 metros que ofrece un día completo de trabajo 100% eléctrico silencioso y semanas enteras con un solo depósito en modo híbrido inteligente.",
    aplicaciones: ["Obras urbanas con restricciones de ruido y humos", "Centros urbanos y hospitales", "Instalaciones industriales"],
    destacados: ["Modo 100% eléctrico o híbrido diésel", "Carga dual 300 kg / 227 kg", "Motores de tracción AC sellados"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "haulotte-ht28-rtj-pro",
    slug: "haulotte-ht28-rtj-pro-4x4",
    marca: "Haulotte",
    modelo: "HT28 RTJ PRO 4x4",
    familia: "elevacion",
    subcategoriaSlug: "brazos-telescopicos",
    lineas: ["alquiler"],
    destacada: false,
    orden: 150,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(27.9),
      alcanceHorizontal: est(23.85),
      capacidadCarga: est(350),
      anchoTransporte: est(2480),
      alturaTransporte: est(2850),
      longitudTransporte: est(13050),
      peso: est(18100),
      pendienteSuperable: est("45%"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Brazo telescópico diésel de 28 metros con el mayor alcance horizontal de su categoría (23.85 m). Capacidad de doble carga 230/350 kg para máxima productividad en grandes montajes.",
    aplicaciones: ["Montaje de cubiertas y fachadas de gran superficie", "Infraestructuras y puentes", "Centrales de ciclo combinado"],
    destacados: ["Alcance horizontal de 23.85 m", "Capacidad dual de cesta hasta 350 kg", "Giro continuo de torreta 360°"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "jlg-1350sjp",
    slug: "jlg-ultra-boom-1350sjp",
    marca: "JLG",
    modelo: "Ultra Boom 1350SJP",
    familia: "elevacion",
    subcategoriaSlug: "brazos-telescopicos",
    lineas: ["alquiler"],
    destacada: true,
    orden: 160,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "valencia", "sevilla", "portugal"],
    specs: {
      alturaTrabajo: est(43.3),
      alcanceHorizontal: est(24.38),
      capacidadCarga: est(450),
      anchoTransporte: est(2490),
      alturaTransporte: est(3050),
      longitudTransporte: est(14890),
      peso: est(20411),
      pendienteSuperable: est("45%"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Brazo telescópico gigante de 43.3 metros de altura con plumín articulado JibPLUS. Permite acceder a los puntos más altos y difíciles de grandes proyectos de ingeniería y estadios.",
    aplicaciones: ["Rascacielos y estadios deportivos", "Grandes refinerías eólicas y petroquímica", "Infraestructuras aeroportuarias"],
    destacados: ["Altura de trabajo de 43.3 m", "Plumín articulado JibPLUS con giro horizontal", "Capacidad de plataforma de 450 kg"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "jlg-1850sj",
    slug: "jlg-ultra-boom-1850sj",
    marca: "JLG",
    modelo: "Ultra Boom 1850SJ",
    familia: "elevacion",
    subcategoriaSlug: "brazos-telescopicos",
    lineas: ["alquiler"],
    destacada: false,
    orden: 170,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "valencia", "portugal"],
    specs: {
      alturaTrabajo: est(58.56),
      alcanceHorizontal: est(24.38),
      capacidadCarga: est(454),
      anchoTransporte: est(2490),
      alturaTransporte: est(3050),
      longitudTransporte: est(19450),
      peso: est(27179),
      traccion: est("4x4"),
    },
    descripcionCorta: "La plataforma autopropulsada más alta del mercado con 58.5 metros de altura de trabajo (57 m reales de plataforma). Diseñada para sustituir grúas en trabajos de montaje de altura extrema.",
    aplicaciones: ["Grandes obras de ingeniería mundial", "Parques eólicos y torres de telecomunicaciones", "Estructuras de acero de altura extrema"],
    destacados: ["Cota máxima de elevación autopropulsada (58.5 m)", "Ejes extensibles telescópicos", "Pantalla LCD con envolvente de trabajo en cabina"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "socage-forste-24d",
    slug: "socage-forste-24d-speed",
    marca: "Socage",
    modelo: "ForSte 24D Speed",
    familia: "elevacion",
    subcategoriaSlug: "plataformas-sobre-camion",
    lineas: ["alquiler"],
    destacada: false,
    orden: 180,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "sobre-camion",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(23.6),
      alcanceHorizontal: est(12.7),
      capacidadCarga: est(300),
      anchoTransporte: est(2100),
      alturaTransporte: est(2950),
      longitudTransporte: est(6850),
      peso: est(3500),
      traccion: est("sobre-camion"),
    },
    descripcionCorta: "Plataforma articulada sobre camión de 3.500 kg conducible con carnet B. Desplazamiento inmediato entre puntos de trabajo con estabilización automática desde la cesta en pocos segundos.",
    aplicaciones: ["Mantenimiento de alumbrado público", "Instalación de rótulos comerciales", "Poda urbana e intervenciones de urgencia"],
    destacados: ["Carnet de conducir B (3.5 t)", "Estabilización automática SPEED", "300 kg de carga en cesta"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "hinowa-lightlift-20-10",
    slug: "hinowa-lightlift-20-10-performance-iiis",
    marca: "Hinowa",
    modelo: "Lightlift 20.10 Performance IIIS",
    familia: "elevacion",
    subcategoriaSlug: "plataformas-sobre-oruga",
    lineas: ["alquiler"],
    destacada: false,
    orden: 190,
    facetas: {
      energia: "hibrido",
      entornos: ["interior", "exterior"],
      traccion: "oruga",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(20.15),
      alcanceHorizontal: est(9.7),
      capacidadCarga: est(230),
      anchoTransporte: est(790),
      alturaTransporte: est(1990),
      longitudTransporte: est(5010),
      peso: est(2840),
      traccion: est("oruga"),
    },
    descripcionCorta: "Plataforma tipo araña sobre orugas de 20 metros con motor bi-energía (gasolina/diésel + motor eléctrico 230V). Pasa por puertas de 80 cm y trabaja sobre forjados con baja presión sobre el suelo.",
    aplicaciones: ["Catedrales, iglesias y museos", "Patios interiores y jardines", "Forjados y pavimentos delicados"],
    destacados: ["Pasa por puertas de 79 cm", "Orugas antihuella ensanchables", "Bi-energía: Diésel / Eléctrico 230V"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["altura"],
  },
  {
    id: "manitou-mt-625",
    slug: "manitou-mt-625-h-easy",
    marca: "Manitou",
    modelo: "MT 625 H Easy",
    familia: "manipulacion",
    subcategoriaSlug: "manipuladores-telescopicos-rigidos",
    lineas: ["alquiler"],
    destacada: false,
    orden: 200,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(5.85),
      alcanceHorizontal: est(3.4),
      capacidadCarga: est(2500),
      anchoTransporte: est(1810),
      alturaTransporte: est(1920),
      longitudTransporte: est(3900),
      peso: est(4800),
      traccion: est("4x4"),
    },
    descripcionCorta: "Manipulador telescópico supercompacto de 6 metros y 2.500 kg de capacidad. Sus reducidas dimensiones de menos de 2 metros de alto permiten acceder a parkings subterráneos y pasos bajos.",
    aplicaciones: ["Parkings subterráneos y naves bajas", "Obras de rehabilitación en cascos históricos", "Sector agrícola y ganadero"],
    destacados: ["Altura de solo 1.92 m", "4 ruedas directrices con 3 modos de dirección", "Transmisión hidrostática"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["cargas"],
  },
  {
    id: "manitou-mt-1440",
    slug: "manitou-mt-1440-easy-st5",
    marca: "Manitou",
    modelo: "MT 1440 Easy ST5",
    familia: "manipulacion",
    subcategoriaSlug: "manipuladores-telescopicos-rigidos",
    lineas: ["alquiler"],
    destacada: true,
    orden: 210,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(13.53),
      alcanceHorizontal: est(9.46),
      capacidadCarga: est(4000),
      anchoTransporte: est(2370),
      alturaTransporte: est(2450),
      longitudTransporte: est(6130),
      peso: est(10890),
      traccion: est("4x4"),
    },
    descripcionCorta: "Manipulador telescópico de 14 metros y 4.000 kg de capacidad con estabilizadores frontales. Es el referente en edificación para elevación de palets de ladrillo y hormigón hasta 4 plantas.",
    aplicaciones: ["Edificación residencial de media altura", "Descarga y acopio de materiales en obra", "Montaje de cubiertas y forjados"],
    destacados: ["Capacidad de 4.000 kg a 14 m", "Estabilizadores hidráulicos de despliegue rápido", "Cabina ergonómica con joystick JSM"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["cargas"],
  },
  {
    id: "manitou-mrt-2150",
    slug: "manitou-mrt-2150-privilege-giratorio",
    marca: "Manitou",
    modelo: "MRT 2150 Privilege + (Giratorio)",
    familia: "manipulacion",
    subcategoriaSlug: "manipuladores-telescopicos-giratorios",
    lineas: ["alquiler"],
    destacada: true,
    orden: 220,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(20.6),
      alcanceHorizontal: est(17.9),
      capacidadCarga: est(5000),
      anchoTransporte: est(2490),
      alturaTransporte: est(3050),
      longitudTransporte: est(6870),
      peso: est(17930),
      traccion: est("4x4"),
    },
    descripcionCorta: "Manipulador telescópico rotativo 360° de 21 metros y 5.000 kg. Combina en una sola máquina las funciones de manipulador telescópico, grúa móvil y plataforma elevadora de personal.",
    aplicaciones: ["Obras de edificación sin espacio para mover máquinas", "Estructuras de hormigón y acero prefabricado", "Sustitución de grúas torre"],
    destacados: ["Rotación 360° continua", "Reconocimiento automático de implementos E-RECO", "Cabina inclinable"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["cargas"],
  },
  {
    id: "jungheinrich-efg-216k",
    slug: "jungheinrich-efg-216k",
    marca: "Jungheinrich",
    modelo: "EFG 216k",
    familia: "manipulacion",
    subcategoriaSlug: "carretillas-electricas",
    lineas: ["venta"],
    condicionVenta: "nueva",
    destacada: true,
    orden: 230,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      capacidadCarga: est(1600),
      alturaTrabajo: est(6.5),
      anchoTransporte: est(1060),
      alturaTransporte: est(2100),
      longitudTransporte: est(1890),
      peso: est(2950),
      traccion: est("2x4"),
    },
    descripcionCorta: "Carretilla elevadora eléctrica contrapesada de 3 ruedas y 1.600 kg. Máxima agilidad de giro y eficiencia energética con tecnología trifásica para la intralogística más exigente.",
    aplicaciones: ["Carga y descarga de camiones", "Almacenamiento en estanterías convencionales", "Alimentación de líneas de producción"],
    destacados: ["Tecnología PureEnergy con bajo consumo", "Dirección asistida eléctrica con volante ergonómico", "Frenado regenerativo"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["cargas"],
  },
  {
    id: "manitou-mc-25-4",
    slug: "manitou-mc-25-4-buggie-todoterreno",
    marca: "Manitou",
    modelo: "MC 25-4 Buggie Todoterreno",
    familia: "manipulacion",
    subcategoriaSlug: "carretillas-todoterreno",
    lineas: ["alquiler"],
    destacada: false,
    orden: 240,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      capacidadCarga: est(2500),
      alturaTrabajo: est(4.5),
      anchoTransporte: est(1450),
      alturaTransporte: est(2150),
      longitudTransporte: est(3045),
      peso: est(4160),
      traccion: est("4x4"),
    },
    descripcionCorta: "Carretilla todoterreno 4x4 compacta de 2.500 kg de capacidad. Diseñada para circular sobre barro, zanjas y pavimentos irregulares con alta velocidad y seguridad para la carga.",
    aplicaciones: ["Eventos al aire libre y festivales", "Patios de materiales de construcción y madereras", "Sector hortofrutícola y explotaciones"],
    destacados: ["Tracción 4x4 desconectable", "Altura libre al suelo de 30 cm", "Radio de giro de 3.4 m"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["cargas"],
  },
  {
    id: "takeuchi-tb216",
    slug: "takeuchi-tb216-canopy",
    marca: "Takeuchi",
    modelo: "TB216 Canopy",
    familia: "movimiento-tierras",
    subcategoriaSlug: "miniexcavadoras",
    lineas: ["alquiler"],
    destacada: false,
    orden: 250,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "oruga",
      requiereFormacion: false,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      peso: est(1770),
      profundidadExcavacion: est(2.39),
      anchoTransporte: est(980),
      alturaTransporte: est(2360),
      longitudTransporte: est(3870),
      potencia: est("11.5 kW (15.6 CV)"),
      traccion: est("oruga"),
    },
    descripcionCorta: "Miniexcavadora de 1.8 toneladas con carro ensanchable hidráulico de 98 a 130 cm. Perfecta para zanjeo de acometidas en aceras y jardinería con precisión milimétrica.",
    aplicaciones: ["Zanjas para conducciones de gas, luz y fibra", "Demolición interior y reformas", "Trabajos de jardinería y piscinas"],
    destacados: ["Carro retráctil de 980 a 1300 mm", "Profundidad de excavación de 2.39 m", "Línea auxiliar de martillo"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["tierra"],
  },
  {
    id: "takeuchi-tb290",
    slug: "takeuchi-tb290-2-cabina",
    marca: "Takeuchi",
    modelo: "TB290-2 Cabina",
    familia: "movimiento-tierras",
    subcategoriaSlug: "miniexcavadoras",
    lineas: ["alquiler"],
    destacada: true,
    orden: 260,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "oruga",
      requiereFormacion: false,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      peso: est(8400),
      profundidadExcavacion: est(4.58),
      anchoTransporte: est(2200),
      alturaTransporte: est(2550),
      longitudTransporte: est(7030),
      potencia: est("51.6 kW (70 CV)"),
      traccion: est("oruga"),
    },
    descripcionCorta: "Excavadora de 9 toneladas con brazo articulado de gran alcance y potencia hidráulica para martillo e implementos pesados. Máxima fuerza de desgarro para saneamientos y urbanizaciones.",
    aplicaciones: ["Urbanizaciones y alcantarillado", "Excavación de cimentaciones", "Demolición pesada"],
    destacados: ["Profundidad de excavación de 4.58 m", "Cabina presurizada con climatizador", "Válvulas de seguridad en pluma y balancín"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["tierra"],
  },
  {
    id: "jcb-3cx",
    slug: "jcb-3cx-eco-sitemaster",
    marca: "JCB",
    modelo: "3CX Eco Sitemaster",
    familia: "movimiento-tierras",
    subcategoriaSlug: "retrocargadoras",
    lineas: ["alquiler"],
    destacada: true,
    orden: 270,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: false,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      peso: est(8135),
      profundidadExcavacion: est(5.46),
      anchoTransporte: est(2350),
      alturaTransporte: est(3610),
      longitudTransporte: est(5620),
      potencia: est("81 kW (109 CV)"),
      traccion: est("4x4"),
    },
    descripcionCorta: "La máquina mixta por excelencia para todo tipo de obras civiles. Desplazamiento por carretera a 40 km/h, pala delantera 6 en 1 con horquillas y retro extensible.",
    aplicaciones: ["Obras públicas y canalizaciones", "Mantenimiento de carreteras", "Carga de camiones y limpieza de viales"],
    destacados: ["Pala delantera 6 en 1", "Brazo extensible Extradig a 5.46 m", "Homologada para circular por carretera"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["tierra"],
  },
  {
    id: "ausa-d-150-ahg",
    slug: "ausa-d-150-ahg-4x4",
    marca: "Ausa",
    modelo: "D 150 AHG 4x4",
    familia: "movimiento-tierras",
    subcategoriaSlug: "dumpers-4x4",
    lineas: ["alquiler"],
    destacada: false,
    orden: 280,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: false,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      capacidadCarga: est(1500),
      peso: est(1510),
      anchoTransporte: est(1480),
      alturaTransporte: est(2580),
      longitudTransporte: est(3240),
      potencia: est("18.5 kW"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Dumper articulado 4x4 de 1.500 kg de carga con tolva giratoria 180°. Muy ágil para verter hormigón o tierra lateralmente sin tener que maniobrar toda la máquina.",
    aplicaciones: ["Transporte de hormigón en zanjas", "Relleno de cimientos", "Reformas urbanas"],
    destacados: ["Tolva giratoria 180°", "Tracción 4x4 permanente", "Transmisión hidrostática"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["tierra"],
  },
  {
    id: "bomag-bt-65",
    slug: "bomag-bt-65",
    marca: "Bomag",
    modelo: "BT 65",
    familia: "compactacion",
    subcategoriaSlug: "pisones",
    lineas: ["alquiler"],
    destacada: false,
    orden: 290,
    facetas: {
      energia: "gasolina",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: false,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      peso: est(68),
      anchoTransporte: est(280),
      alturaTransporte: est(1030),
      longitudTransporte: est(728),
      potencia: est("2.8 kW (Honda GX100)"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Pisón vibrante de 68 kg para compactación de suelos cohesivos y mixtos en zanjas profundas de canalización de tuberías y cimientos.",
    aplicaciones: ["Zanjas estrechas y canalizaciones", "Bases para bordillos y aceras", "Compactación perimetral de cimientos"],
    destacados: ["Fuerza de impacto de 17 kN", "Sistema de protección de bajo nivel de aceite", "Empuñadura antivibratoria"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["tierra"],
  },
  {
    id: "bomag-bw-120-ad",
    slug: "bomag-bw-120-ad-5",
    marca: "Bomag",
    modelo: "BW 120 AD-5",
    familia: "compactacion",
    subcategoriaSlug: "rodillos",
    lineas: ["alquiler"],
    destacada: false,
    orden: 300,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: false,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      peso: est(2700),
      anchoTransporte: est(1270),
      alturaTransporte: est(2560),
      longitudTransporte: est(2529),
      potencia: est("25 kW (Kubota)"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Rodillo tándem articulado de 2.7 toneladas y 1.20 metros de ancho de tambor con sistema de riego a presión. Diseñado para pavimentación asfáltica y compactación de explanadas.",
    aplicaciones: ["Pavimentación de calles y aparcamientos", "Caminos rurales y pistas deportivas", "Reparación de firmes asfálticos"],
    destacados: ["Doble tambor vibrante", "Riego por aspersión a presión con filtro", "Compactación de hasta 36 kN"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["tierra"],
  },
  {
    id: "pramac-gsw-60",
    slug: "pramac-gsw-60-kva-insonorizado",
    marca: "Pramac",
    modelo: "GSW 60 kVA Insonorizado",
    familia: "energia",
    subcategoriaSlug: "grupos-electrogenos",
    lineas: ["alquiler"],
    destacada: true,
    orden: 310,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: false,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      potencia: est("60 kVA (48 kW)"),
      voltaje: est("400V / 230V Trifásico"),
      peso: est(1150),
      anchoTransporte: est(1000),
      alturaTransporte: est(1450),
      longitudTransporte: est(2200),
      autonomia: est("18 horas (75% carga)"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Grupo electrógeno diésel insonorizado de 60 kVA (48 kW). Suministro continuo para grúas torre, bombeo de hormigón y casetas de obra con cuadro de tomas protegido.",
    aplicaciones: ["Obras de edificación sin acometida eléctrica", "Respaldo de emergencia en plantas industriales", "Eventos y espectáculos"],
    destacados: ["Insonorización a 65 dB(A) a 7 m", "Depósito de gran capacidad integrado", "Cuadro digital con protección magnetotérmica y diferencial"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["energia"],
  },
  {
    id: "atlas-copco-qas-150",
    slug: "atlas-copco-qas-150-kva",
    marca: "Atlas Copco",
    modelo: "QAS 150 kVA",
    familia: "energia",
    subcategoriaSlug: "grupos-electrogenos",
    lineas: ["alquiler"],
    destacada: false,
    orden: 320,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: false,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      potencia: est("150 kVA (120 kW)"),
      voltaje: est("400V / 230V Trifásico"),
      peso: est(2800),
      anchoTransporte: est(1180),
      alturaTransporte: est(1710),
      longitudTransporte: est(3380),
      autonomia: est("14 horas continuas"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Grupo electrógeno de 150 kVA preparado para trabajos continuos severos en construcción pesada, túneles e industrias. Carrocería de acero galvanizado anticorrosión.",
    aplicaciones: ["Grandes obras de infraestructuras", "Paradas técnicas en refinerías e industrias", "Respaldo hospitalario e infraestructuras críticas"],
    destacados: ["Motor Volvo / Cummins de alta fiabilidad", "Conexión paralela y sincronización automática", "Bandeja de retención de fluidos al 110%"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["energia"],
  },
  {
    id: "atlas-copco-hilight-v4",
    slug: "atlas-copco-hilight-v4-led",
    marca: "Atlas Copco",
    modelo: "HiLight V4+ LED",
    familia: "energia",
    subcategoriaSlug: "torres-iluminacion",
    lineas: ["alquiler"],
    destacada: true,
    orden: 330,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: false,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      alturaTrabajo: est(7.5),
      potencia: est("4 x 350 W LED (4.000 m²)"),
      peso: est(710),
      anchoTransporte: est(1160),
      alturaTransporte: est(2500),
      longitudTransporte: est(1670),
      autonomia: est("140 horas por depósito"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Torre de iluminación móvil con 4 focos LED de 350W montados sobre mástil telescópico hidráulico de 7.5 metros. Ilumina un área de 4.000 m² con hasta 140 horas de autonomía por depósito.",
    aplicaciones: ["Turnos nocturnos en autopistas y ferrocarril", "Obras de emergencia y rescate", "Eventos y festivales"],
    destacados: ["Consumo ultra bajo (0.5 l/h)", "Mástil vertical con elevación asistida", "Resistencia a vientos de hasta 80 km/h"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["energia"],
  },
  {
    id: "atlas-copco-xas-88",
    slug: "atlas-copco-xas-88-hardhat",
    marca: "Atlas Copco",
    modelo: "XAS 88 HardHat",
    familia: "aire-martillos",
    subcategoriaSlug: "compresores-portatiles",
    lineas: ["alquiler"],
    destacada: false,
    orden: 340,
    facetas: {
      energia: "diesel",
      entornos: ["exterior"],
      traccion: "4x4",
      requiereFormacion: false,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      caudalAire: est("5.0 m³/min (175 cfm)"),
      presionAire: est("7 bar"),
      peso: est(749),
      anchoTransporte: est(1350),
      alturaTransporte: est(1250),
      longitudTransporte: est(2290),
      potencia: est("33 kW (Kubota)"),
      traccion: est("4x4"),
    },
    descripcionCorta: "Compresor portátil remolcable de 5.0 m³/min a 7 bar de presión con capota HardHat de polietileno ultrarresistente. Alimenta simultáneamente dos martillos demoledores pesados.",
    aplicaciones: ["Alimentación de martillos picadores y demoledores", "Chorreo de arena y limpieza de fachadas", "Soplado y pruebas de presión"],
    destacados: ["Peso inferior a 750 kg (arrastre sin carnet especial)", "Capota antichoque HardHat®", "Generador eléctrico auxiliar opcional"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["energia"],
  },
  {
    id: "jungheinrich-efg-320",
    slug: "jungheinrich-efg-320-4-ruedas",
    marca: "Jungheinrich",
    modelo: "EFG 320 (4 Ruedas)",
    familia: "manipulacion",
    subcategoriaSlug: "carretillas-electricas",
    lineas: ["venta"],
    condicionVenta: "nueva",
    destacada: false,
    orden: 350,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      capacidadCarga: est(2000),
      alturaTrabajo: est(7),
      anchoTransporte: est(1120),
      alturaTransporte: est(2160),
      longitudTransporte: est(2070),
      peso: est(3450),
      traccion: est("2x4"),
    },
    descripcionCorta: "Carretilla elevadora contrapesada eléctrica de 4 ruedas y 2.000 kg. Máxima estabilidad en curvas con Jungheinrich Curve Control y opciones de batería Li-Ion para cargas intermedias rápidas.",
    aplicaciones: ["Operativa intensiva de almacén 24/7", "Alimentación de líneas industriales", "Carga en rampas y muelles"],
    destacados: ["Opción Tecnología Ión-Litio", "Curve Control activo para reducción de velocidad en giro", "Garantía oficial Jofemesa"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["cargas"],
  },
  {
    id: "jungheinrich-eje-116",
    slug: "jungheinrich-eje-116-transpaleta-electrica",
    marca: "Jungheinrich",
    modelo: "EJE 116 (Transpaleta Eléctrica)",
    familia: "manipulacion",
    subcategoriaSlug: "carretillas-electricas",
    lineas: ["venta"],
    condicionVenta: "reacondicionada",
    destacada: false,
    orden: 360,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      capacidadCarga: est(1600),
      alturaTrabajo: est(0.2),
      anchoTransporte: est(720),
      alturaTransporte: est(1250),
      longitudTransporte: est(1640),
      peso: est(490),
      traccion: est("2x4"),
    },
    descripcionCorta: "Transpaleta eléctrica de conductor acompañante de 1.600 kg. Extremadamente compacta, diseñada para mover palets en espacios muy reducidos de camiones y pasillos de tienda.",
    aplicaciones: ["Descarga en muelle y plataforma elevadora de camión", "Comercio minorista y supermercados", "Transporte horizontal rápido"],
    destacados: ["Timón de seguridad ergonómico", "Cargador integrado de batería", "Ruedas de apoyo amortiguadas"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["cargas"],
  },
  {
    id: "jungheinrich-ejc-112",
    slug: "jungheinrich-ejc-112-apilador-electrico",
    marca: "Jungheinrich",
    modelo: "EJC 112 (Apilador Eléctrico)",
    familia: "manipulacion",
    subcategoriaSlug: "carretillas-electricas",
    lineas: ["venta"],
    condicionVenta: "reacondicionada",
    destacada: false,
    orden: 370,
    facetas: {
      energia: "electrico",
      entornos: ["interior", "exterior"],
      traccion: "2x4",
      requiereFormacion: true,
    },
    delegaciones: ["madrid", "asturias", "valencia", "sevilla", "valladolid", "alicante", "malaga", "castellon", "portugal"],
    specs: {
      capacidadCarga: est(1200),
      alturaTrabajo: est(4.7),
      anchoTransporte: est(800),
      alturaTransporte: est(1950),
      longitudTransporte: est(1845),
      peso: est(980),
      traccion: est("2x4"),
    },
    descripcionCorta: "Apilador eléctrico de conductor acompañante con capacidad de 1.200 kg y elevación de hasta 4.70 metros. Ideal para almacenar palets en estanterías medias con máxima seguridad.",
    aplicaciones: ["Almacenes medianos y trastiendas", "Apilado y desapilado de palets", "Picking en altura"],
    destacados: ["Mástil panorámico para visibilidad óptima", "Elevación proporcional electrohidráulica", "Totalmente reacondicionada y certificada"],
    imagenes: [],
    fichaTecnica: null,
    trabajos: ["cargas"],
  },
];
